services:
  - type: web
    name: pandaco
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pandaco_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False